apiVersion: apps/v1
kind: Deployment

metadata:
  name: lightweight-app

spec:
  replicas: 1

  selector:
    matchLabels:
      app: lightweight-app

  template:
    metadata:
      labels:
        app: lightweight-app

    spec:
      containers:
      - name: lightweight-app
        image: jaykona28/lightweight-app:v1

        resources:
          requests:
            memory: "64Mi"
            cpu: "100m"

          limits:
            memory: "128Mi"
            cpu: "200m"

        ports:
        - containerPort: 5000
